"""
ME Statistics — PDF Report Generator
========================================
ReportLab-based PDF builder for individual and team reports.
Branded with department colors and teal palette.
"""

import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from sqlalchemy import func
from app.extensions import db
from app.models import User, MonthlyReport, Goal, Task, SystemConfig

# ── Color Palette (matching app design) ─────────────────────
TEAL = HexColor('#0D9488')
TEAL_LIGHT = HexColor('#5EEAD4')
TEAL_BG = HexColor('#F0FDFA')
PINE = HexColor('#064E3B')
SUCCESS = HexColor('#10B981')
WARNING = HexColor('#F59E0B')
TEXT_PRIMARY = HexColor('#1F2937')
TEXT_MUTED = HexColor('#6B7280')
HEADER_BG = HexColor('#0D9488')
ROW_ALT = HexColor('#F0FDFA')

MONTH_NAMES = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
]


def _get_styles():
    """Create custom paragraph styles."""
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        'ReportTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=PINE,
        spaceAfter=6,
        fontName='Helvetica-Bold',
    ))
    styles.add(ParagraphStyle(
        'SectionTitle',
        parent=styles['Heading2'],
        fontSize=13,
        textColor=TEAL,
        spaceBefore=16,
        spaceAfter=8,
        fontName='Helvetica-Bold',
    ))
    styles.add(ParagraphStyle(
        'FooterStyle',
        parent=styles['Normal'],
        fontSize=8,
        textColor=TEXT_MUTED,
        alignment=TA_CENTER,
    ))
    styles.add(ParagraphStyle(
        'SubInfo',
        parent=styles['Normal'],
        fontSize=9,
        textColor=TEXT_MUTED,
        spaceAfter=12,
    ))
    return styles


def _header_table_style():
    """Table style for data tables with teal headers."""
    return TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_BG),
        ('TEXTCOLOR', (0, 0), (-1, 0), white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#D1D5DB')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [white, ROW_ALT]),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ])


def _build_header(story, styles, title, subtitle=None):
    """Add branded header to the PDF."""
    dept = SystemConfig.get('department_name', 'Medication Error')
    story.append(Paragraph(dept, styles['ReportTitle']))
    if subtitle:
        story.append(Paragraph(subtitle, styles['SubInfo']))
    story.append(HRFlowable(
        width="100%", thickness=2, color=TEAL,
        spaceBefore=2, spaceAfter=12
    ))


def _build_footer(canvas, doc, generated_by=None):
    """Draw footer on each page."""
    canvas.saveState()
    canvas.setFont('Helvetica', 7)
    canvas.setFillColor(TEXT_MUTED)
    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    footer_left = f"Generated: {now}"
    footer_right = f"Page {doc.page}"
    if generated_by:
        footer_left = f"Generated by {generated_by} — {now}"
    canvas.drawString(40, 25, footer_left)
    canvas.drawRightString(A4[0] - 40, 25, footer_right)
    canvas.restoreState()


def build_user_pdf(user, year, generated_by=None):
    """
    Generate a PDF report for a single user.

    Args:
        user: User model instance
        year: Report year
        generated_by: Name of admin who generated the PDF

    Returns:
        BytesIO object containing the PDF
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=30 * mm, rightMargin=30 * mm,
        topMargin=25 * mm, bottomMargin=25 * mm,
    )
    styles = _get_styles()
    story = []

    # Header
    _build_header(
        story, styles,
        f'{user.full_name} — Performance Report',
        f'Year: {year} | Monthly Target: {user.monthly_target}'
    )

    # ── Monthly Reports Table ─────────────────────────────────
    story.append(Paragraph('Monthly Reports', styles['SectionTitle']))

    reports = MonthlyReport.query.filter_by(
        user_id=user.id, year=year, approval_status='approved'
    ).order_by(MonthlyReport.month).all()

    report_map = {r.month: r for r in reports}
    table_data = [['Month', 'Reports', 'Target', 'Gap', 'Achievement']]
    ytd_total = 0

    for m in range(1, 13):
        r = report_map.get(m)
        count = r.report_count if r else 0
        target = r.target_snapshot if r else user.monthly_target
        gap = count - target if target > 0 else '—'
        ach = f'{round((count / target) * 100, 1)}%' if target > 0 else 'N/A'
        ytd_total += count
        table_data.append([MONTH_NAMES[m - 1], str(count), str(target), str(gap), ach])

    table_data.append(['YTD Total', str(ytd_total), '', '', ''])

    col_widths = [70, 70, 70, 70, 80]
    t = Table(table_data, colWidths=col_widths)
    t.setStyle(_header_table_style())
    # Bold the YTD row
    t.setStyle(TableStyle([
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('BACKGROUND', (0, -1), (-1, -1), TEAL_BG),
    ]))
    story.append(t)
    story.append(Spacer(1, 12))

    # ── Goals Table ───────────────────────────────────────────
    goals = Goal.query.filter_by(
        user_id=user.id, approval_status='approved'
    ).order_by(Goal.created_at.desc()).all()

    if goals:
        story.append(Paragraph('Goals', styles['SectionTitle']))
        goal_data = [['Title', 'KPI', 'Status', 'Progress', 'Priority']]
        for g in goals:
            goal_data.append([
                g.title[:40],
                (g.kpi or '—')[:30],
                g.status.replace('_', ' ').title(),
                f'{g.progress}%',
                g.priority.title(),
            ])
        gt = Table(goal_data, colWidths=[130, 100, 70, 60, 60])
        gt.setStyle(_header_table_style())
        story.append(gt)
        story.append(Spacer(1, 12))

    # ── Tasks Table ───────────────────────────────────────────
    tasks = Task.query.filter_by(user_id=user.id).order_by(Task.created_at.desc()).all()

    if tasks:
        story.append(Paragraph('Tasks', styles['SectionTitle']))
        task_data = [['Description', 'Status', 'Progress', 'Priority']]
        for t_item in tasks:
            task_data.append([
                t_item.description[:50],
                t_item.status.replace('_', ' ').title(),
                f'{t_item.progress}%',
                t_item.priority.title(),
            ])
        tt = Table(task_data, colWidths=[200, 80, 60, 60])
        tt.setStyle(_header_table_style())
        story.append(tt)

    # Build PDF with footer
    doc.build(story, onFirstPage=lambda c, d: _build_footer(c, d, generated_by),
              onLaterPages=lambda c, d: _build_footer(c, d, generated_by))
    buffer.seek(0)
    return buffer


def build_team_pdf(year, generated_by=None):
    """
    Generate a PDF team summary report.

    Args:
        year: Report year
        generated_by: Name of admin who generated the PDF

    Returns:
        BytesIO object containing the PDF
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=25 * mm, rightMargin=25 * mm,
        topMargin=25 * mm, bottomMargin=25 * mm,
    )
    styles = _get_styles()
    story = []

    # Header
    _build_header(
        story, styles,
        'Team Performance Summary',
        f'Year: {year}'
    )

    users = User.query.filter_by(is_active=True, is_approved=True).all()

    # ── Leaderboard Table ─────────────────────────────────────
    story.append(Paragraph('Leaderboard', styles['SectionTitle']))
    board_data = [['Rank', 'Name', 'YTD Total', 'Avg Monthly', 'Target', 'Achievement']]

    board = []
    for u in users:
        ytd = db.session.query(
            func.coalesce(func.sum(MonthlyReport.report_count), 0)
        ).filter(
            MonthlyReport.user_id == u.id,
            MonthlyReport.year == year,
            MonthlyReport.approval_status == 'approved'
        ).scalar()

        months_with_data = MonthlyReport.query.filter_by(
            user_id=u.id, year=year, approval_status='approved'
        ).count()

        avg = round(ytd / months_with_data, 1) if months_with_data > 0 else 0
        target_yearly = u.monthly_target * 12
        ach = f'{round((ytd / target_yearly) * 100, 1)}%' if target_yearly > 0 else 'N/A'
        board.append((u.full_name, ytd, avg, u.monthly_target, ach))

    board.sort(key=lambda x: x[1], reverse=True)
    for rank, (name, ytd, avg, target, ach) in enumerate(board, 1):
        board_data.append([str(rank), name, str(ytd), str(avg), str(target), ach])

    bt = Table(board_data, colWidths=[40, 120, 65, 65, 55, 75])
    bt.setStyle(_header_table_style())
    story.append(bt)
    story.append(Spacer(1, 16))

    # ── Monthly Breakdown ─────────────────────────────────────
    story.append(Paragraph('Monthly Breakdown', styles['SectionTitle']))
    header_row = ['Name'] + MONTH_NAMES + ['YTD']
    breakdown_data = [header_row]

    for u in users:
        reports = MonthlyReport.query.filter_by(
            user_id=u.id, year=year, approval_status='approved'
        ).all()
        row = [0] * 12
        for r in reports:
            row[r.month - 1] = r.report_count
        breakdown_data.append([u.full_name[:15]] + [str(x) for x in row] + [str(sum(row))])

    col_w = [75] + [30] * 12 + [35]
    mt = Table(breakdown_data, colWidths=col_w)
    mt.setStyle(_header_table_style())
    mt.setStyle(TableStyle([
        ('FONTSIZE', (0, 0), (-1, -1), 7),
    ]))
    story.append(mt)

    # Build PDF with footer
    doc.build(story, onFirstPage=lambda c, d: _build_footer(c, d, generated_by),
              onLaterPages=lambda c, d: _build_footer(c, d, generated_by))
    buffer.seek(0)
    return buffer
