"""Route handlers for individual and team data exports."""

from __future__ import annotations

from datetime import datetime
from io import BytesIO
from typing import Dict, List, Sequence, Tuple

from flask import abort, send_file
from flask.typing import ResponseReturnValue
from flask_login import current_user, login_required

from app.auth.decorators import active_required, admin_required
from app.export import export_bp
from app.export.generators import (
    generate_individual_pdf,
    generate_individual_xlsx,
    generate_team_pdf,
    generate_team_xlsx,
)
from app.models import ApprovalStatus, Goal, MonthlyReport, Task, User, UserRole
from app.services.system_config import get_config_value


def _period_month_range(
    period: str,
    month: int,
    custom_from: int,
    custom_to: int,
) -> Tuple[int, int]:
    """Resolve month start/end boundaries from period parameters.

    Args:
        period: Period token (`month`, `quarter`, `year`, `custom`).
        month: Selected month used for month/quarter modes.
        custom_from: Start month for custom period.
        custom_to: End month for custom period.

    Returns:
        Tuple[int, int]: Inclusive start and end month numbers.

    Side Effects:
        None.

    Raises:
        ValueError: When period parameters are invalid.
    """

    if period == "month":
        return month, month

    if period == "quarter":
        start_month = ((month - 1) // 3) * 3 + 1
        return start_month, start_month + 2

    if period == "year":
        return 1, 12

    if period == "custom":
        if custom_from < 1 or custom_to > 12 or custom_from > custom_to:
            raise ValueError("Invalid custom month range.")
        return custom_from, custom_to

    raise ValueError("Invalid export period.")


def _parse_export_params() -> Tuple[str, int, int, int]:
    """Parse and validate shared export query parameters.

    Args:
        None.

    Returns:
        Tuple[str, int, int, int]: format, year, start_month, end_month.

    Side Effects:
        Reads request query values.

    Raises:
        werkzeug.exceptions.BadRequest: When parameters are invalid.
    """

    from flask import request

    export_format = str(request.args.get("format", "xlsx")).strip().lower()
    if export_format not in {"xlsx", "pdf"}:
        abort(400)

    year_raw = str(request.args.get("year", datetime.utcnow().year)).strip()
    if not year_raw.isdigit():
        abort(400)
    year = int(year_raw)

    period = str(request.args.get("period", "year")).strip().lower()

    month_raw = str(request.args.get("month", datetime.utcnow().month)).strip()
    custom_from_raw = str(request.args.get("from", "1")).strip()
    custom_to_raw = str(request.args.get("to", "12")).strip()

    month = int(month_raw) if month_raw.isdigit() else datetime.utcnow().month
    custom_from = int(custom_from_raw) if custom_from_raw.isdigit() else 1
    custom_to = int(custom_to_raw) if custom_to_raw.isdigit() else 12

    try:
        start_month, end_month = _period_month_range(
            period=period,
            month=month,
            custom_from=custom_from,
            custom_to=custom_to,
        )
    except ValueError:
        abort(400)

    return export_format, year, start_month, end_month


def _reports_for_period(user_id: int, year: int, start_month: int, end_month: int) -> List[MonthlyReport]:
    """Load approved monthly reports for a user in selected period.

    Args:
        user_id: Report owner identifier.
        year: Year filter.
        start_month: Inclusive period start month.
        end_month: Inclusive period end month.

    Returns:
        List[MonthlyReport]: Period-filtered report rows.

    Side Effects:
        Executes database query.

    Raises:
        Any SQLAlchemy error raised during query execution.
    """

    return (
        MonthlyReport.query.filter(
            MonthlyReport.user_id == user_id,
            MonthlyReport.year == year,
            MonthlyReport.month >= start_month,
            MonthlyReport.month <= end_month,
            MonthlyReport.approval_status == ApprovalStatus.APPROVED,
        )
        .order_by(MonthlyReport.month.asc())
        .all()
    )


def _download_response(payload: bytes, filename: str, mimetype: str) -> ResponseReturnValue:
    """Build attachment response from generated bytes payload.

    Args:
        payload: Generated file bytes.
        filename: Download filename.
        mimetype: HTTP content type.

    Returns:
        ResponseReturnValue: Flask send_file response object.

    Side Effects:
        None.

    Raises:
        None.
    """

    stream = BytesIO(payload)
    stream.seek(0)
    return send_file(stream, as_attachment=True, download_name=filename, mimetype=mimetype)


@export_bp.get("/my-report")
@login_required
@active_required
def export_my_report() -> ResponseReturnValue:
    """Export current user's reports, goals, and tasks as Excel or PDF.

    Args:
        None.

    Returns:
        ResponseReturnValue: File download response.

    Side Effects:
        Reads current user's records and generates file bytes.

    Raises:
        werkzeug.exceptions.BadRequest: When export parameters are invalid.
    """

    export_format, year, start_month, end_month = _parse_export_params()
    reports = _reports_for_period(
        user_id=current_user.id,
        year=year,
        start_month=start_month,
        end_month=end_month,
    )
    goals = Goal.query.filter_by(user_id=current_user.id).order_by(Goal.id.asc()).all()
    tasks = Task.query.filter_by(user_id=current_user.id).order_by(Task.id.asc()).all()

    department_name = get_config_value("department_name", "Medication Error") or "Medication Error"

    if export_format == "xlsx":
        payload = generate_individual_xlsx(
            user=current_user,
            reports=reports,
            goals=goals,
            tasks=tasks,
        )
        return _download_response(
            payload=payload,
            filename=f"my_report_{year}.xlsx",
            mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )

    payload = generate_individual_pdf(
        user=current_user,
        reports=reports,
        goals=goals,
        tasks=tasks,
        department_name=department_name,
    )
    return _download_response(
        payload=payload,
        filename=f"my_report_{year}.pdf",
        mimetype="application/pdf",
    )


@export_bp.get("/user/<int:user_id>")
@login_required
@active_required
@admin_required
def export_user_report(user_id: int) -> ResponseReturnValue:
    """Export one selected staff member's records as Excel or PDF.

    Args:
        user_id: Target staff identifier.

    Returns:
        ResponseReturnValue: File download response.

    Side Effects:
        Reads target staff records and generates file bytes.

    Raises:
        werkzeug.exceptions.NotFound: When user does not exist.
    """

    export_format, year, start_month, end_month = _parse_export_params()
    user = User.query.get_or_404(user_id)

    reports = _reports_for_period(
        user_id=user.id,
        year=year,
        start_month=start_month,
        end_month=end_month,
    )
    goals = Goal.query.filter_by(user_id=user.id).order_by(Goal.id.asc()).all()
    tasks = Task.query.filter_by(user_id=user.id).order_by(Task.id.asc()).all()
    department_name = get_config_value("department_name", "Medication Error") or "Medication Error"

    if export_format == "xlsx":
        payload = generate_individual_xlsx(user=user, reports=reports, goals=goals, tasks=tasks)
        return _download_response(
            payload=payload,
            filename=f"user_{user.id}_report_{year}.xlsx",
            mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )

    payload = generate_individual_pdf(
        user=user,
        reports=reports,
        goals=goals,
        tasks=tasks,
        department_name=department_name,
    )
    return _download_response(
        payload=payload,
        filename=f"user_{user.id}_report_{year}.pdf",
        mimetype="application/pdf",
    )


@export_bp.get("/team")
@login_required
@active_required
@admin_required
def export_team_report() -> ResponseReturnValue:
    """Export team-level summary as Excel or PDF for administrators.

    Args:
        None.

    Returns:
        ResponseReturnValue: File download response.

    Side Effects:
        Reads team records and generates aggregate export bytes.

    Raises:
        werkzeug.exceptions.BadRequest: When query parameters are invalid.
    """

    export_format, year, start_month, end_month = _parse_export_params()
    staff_users = (
        User.query.filter_by(role=UserRole.USER, is_active=True, is_approved=True)
        .order_by(User.full_name.asc())
        .all()
    )

    reports_by_user: Dict[int, Sequence[MonthlyReport]] = {}
    goals_by_user: Dict[int, Sequence[Goal]] = {}
    for user in staff_users:
        reports_by_user[user.id] = _reports_for_period(
            user_id=user.id,
            year=year,
            start_month=start_month,
            end_month=end_month,
        )
        goals_by_user[user.id] = Goal.query.filter_by(user_id=user.id).all()

    department_name = get_config_value("department_name", "Medication Error") or "Medication Error"

    if export_format == "xlsx":
        payload = generate_team_xlsx(
            users=staff_users,
            reports_by_user=reports_by_user,
            goals_by_user=goals_by_user,
        )
        return _download_response(
            payload=payload,
            filename=f"team_report_{year}.xlsx",
            mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )

    payload = generate_team_pdf(
        users=staff_users,
        reports_by_user=reports_by_user,
        department_name=department_name,
    )
    return _download_response(
        payload=payload,
        filename=f"team_report_{year}.pdf",
        mimetype="application/pdf",
    )
